data:
  bucket: "crypto-historical-price-faadab22"
  bronze_key: "bronze/btc.parquet"

output:
  bucket: "btc-seasonal-analysis-faadab22"
  silver_key: "btc_enriched.parquet"
  gold_key: "btc_seasonal_profile.parquet"


bitcoin_cycle:
  bull_days: 450
  bear_days: 800

  halvings:
    - "2012-11-28"
    - "2016-07-09"
    - "2020-05-11"
    - "2024-04-20"
    - "2028-03-01"